# Hyprland Configuration. https://wiki.hypr.land/Configuring/
# Source all custom configurations.
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/device.conf
source = ~/.config/hypr/conf/monitor.conf
source = ~/.config/hypr/conf/permission.conf
source = ~/.config/hypr/conf/programs.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/workspace.conf
source = ~/.config/hypr/conf/environment.conf
source = ~/.config/hypr/conf/appearance.conf
source = ~/.config/hypr/conf/layout.conf
source = ~/.config/hypr/conf/autostart.conf

