ipc = on
splash = false

wallpaper {
    monitor = DP-1
    path = $HOME/Pictures/Underpass.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = $HOME/Pictures/Underpass.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = $HOME/Pictures/Underpass.jpg
    fit_mode = cover
}

