# Autostart necessary processes (like notification daemons, status bars, etc.)
# https://wiki.hypr.land/Configuring/Keywords#executing

exec-once = waybar 
exec-once = hyprpaper
exec-once = swaync
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprpaper
exec-once = hyprctl setcursor Bibatat-Original-Ice 28

# Automatically start up user applications.
exec-once = [workspace 1 silent] /opt/google/chrome/chrome
exec-once = [workspace 2 silent] /usr/bin/ghostty
exec-once = [workspace 3 silent] /usr/bin/discord
exec-once = [workspace 3 silent] /usr/bin/spotify
exec-once = [workspace 4 silent] /usr/bin/signal-desktop

