# Customize the environment.
# https://wiki.hypr.land/Configuring/Keywords#

env = HYPRCURSOR_THEME,Bibata-Original-Ice
env = HYPRCURSOR_SIZE,28

env = XCURSOR_THEME,Bibata-Original-Ice
env = XCURSOR_SIZE,28

