# Keyboard Layout
# https://wiki.hypr.land/Configuring/Variables#input

input {
    # Mouse configuration.
    follow_mouse = 0
    mouse_refocus = false
    sensitivity = 0

    # Keyboard configuration.
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
}
